//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гости.
    /// </summary>
    // *** Start programmer edit section *** (Гости CustomAttributes)

    // *** End programmer edit section *** (Гости CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостиE", new string[] {
            "КодГостя as \'Код гостя\'",
            "Имя as \'Имя\'",
            "Фамилия as \'Фамилия\'",
            "Отчество as \'Отчество\'"})]
    [View("ГостиL", new string[] {
            "КодГостя as \'Код гостя\'",
            "Имя as \'Имя\'",
            "Фамилия as \'Фамилия\'",
            "Отчество as \'Отчество\'"})]
    public class Гости : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодГостя;
        
        private string fИмя;
        
        private string fФамилия;
        
        private string fОтчество;
        
        // *** Start programmer edit section *** (Гости CustomMembers)

        // *** End programmer edit section *** (Гости CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Имя CustomAttributes)

        // *** End programmer edit section *** (Гости.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Имя Get start)

                // *** End programmer edit section *** (Гости.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Гости.Имя Get end)

                // *** End programmer edit section *** (Гости.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Имя Set start)

                // *** End programmer edit section *** (Гости.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Гости.Имя Set end)

                // *** End programmer edit section *** (Гости.Имя Set end)
            }
        }
        
        /// <summary>
        /// КодГостя.
        /// </summary>
        // *** Start programmer edit section *** (Гости.КодГостя CustomAttributes)

        // *** End programmer edit section *** (Гости.КодГостя CustomAttributes)
        public virtual int КодГостя
        {
            get
            {
                // *** Start programmer edit section *** (Гости.КодГостя Get start)

                // *** End programmer edit section *** (Гости.КодГостя Get start)
                int result = this.fКодГостя;
                // *** Start programmer edit section *** (Гости.КодГостя Get end)

                // *** End programmer edit section *** (Гости.КодГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.КодГостя Set start)

                // *** End programmer edit section *** (Гости.КодГостя Set start)
                this.fКодГостя = value;
                // *** Start programmer edit section *** (Гости.КодГостя Set end)

                // *** End programmer edit section *** (Гости.КодГостя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Отчество CustomAttributes)

        // *** End programmer edit section *** (Гости.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Отчество Get start)

                // *** End programmer edit section *** (Гости.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Гости.Отчество Get end)

                // *** End programmer edit section *** (Гости.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Отчество Set start)

                // *** End programmer edit section *** (Гости.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Гости.Отчество Set end)

                // *** End programmer edit section *** (Гости.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Гости.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Фамилия Get start)

                // *** End programmer edit section *** (Гости.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Гости.Фамилия Get end)

                // *** End programmer edit section *** (Гости.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Фамилия Set start)

                // *** End programmer edit section *** (Гости.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Гости.Фамилия Set end)

                // *** End programmer edit section *** (Гости.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиE", typeof(IIS.Hotel.Гости));
                }
            }
            
            /// <summary>
            /// "ГостиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиL", typeof(IIS.Hotel.Гости));
                }
            }
        }
    }
}
