//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доступ.
    /// </summary>
    // *** Start programmer edit section *** (Доступ CustomAttributes)

    // *** End programmer edit section *** (Доступ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоступE", new string[] {
            "КодДоступа as \'Код доступа\'",
            "Доступ as \'Доступ\'",
            "Комната as \'Комната\'",
            "Комната.Класс as \'Класс\'",
            "Комната.КодКомнаты as \'Код комнаты\'",
            "Комната.КолвоМест as \'Колво мест\'",
            "Комната.Стоимость as \'Стоимость\'"}, Hidden=new string[] {
            "Комната.Класс",
            "Комната.КодКомнаты",
            "Комната.КолвоМест",
            "Комната.Стоимость"})]
    [AssociatedDetailViewAttribute("ДоступE", "РегистрЗаписи", "РегистрЗаписиE", true, "", "Регистр записи", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДоступE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Класс")]
    [View("ДоступL", new string[] {
            "КодДоступа as \'Код доступа\'",
            "Доступ as \'Доступ\'",
            "Комната.Класс as \'Класс\'",
            "Комната.КодКомнаты as \'Код комнаты\'",
            "Комната.КолвоМест as \'колво мест\'",
            "Комната.Стоимость as \'Стоимость\'"})]
    public class Доступ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДоступа;
        
        private string fДоступ;
        
        private IIS.Hotel.Комната fКомната;
        
        private IIS.Hotel.DetailArrayOfРегистрЗаписи fРегистрЗаписи;
        
        // *** Start programmer edit section *** (Доступ CustomMembers)

        // *** End programmer edit section *** (Доступ CustomMembers)

        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Доступ CustomAttributes)

        // *** End programmer edit section *** (Доступ.Доступ CustomAttributes)
        [StrLen(255)]
        public virtual string Доступ
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Доступ Get start)

                // *** End programmer edit section *** (Доступ.Доступ Get start)
                string result = this.fДоступ;
                // *** Start programmer edit section *** (Доступ.Доступ Get end)

                // *** End programmer edit section *** (Доступ.Доступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Доступ Set start)

                // *** End programmer edit section *** (Доступ.Доступ Set start)
                this.fДоступ = value;
                // *** Start programmer edit section *** (Доступ.Доступ Set end)

                // *** End programmer edit section *** (Доступ.Доступ Set end)
            }
        }
        
        /// <summary>
        /// КодДоступа.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.КодДоступа CustomAttributes)

        // *** End programmer edit section *** (Доступ.КодДоступа CustomAttributes)
        public virtual int КодДоступа
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.КодДоступа Get start)

                // *** End programmer edit section *** (Доступ.КодДоступа Get start)
                int result = this.fКодДоступа;
                // *** Start programmer edit section *** (Доступ.КодДоступа Get end)

                // *** End programmer edit section *** (Доступ.КодДоступа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.КодДоступа Set start)

                // *** End programmer edit section *** (Доступ.КодДоступа Set start)
                this.fКодДоступа = value;
                // *** Start programmer edit section *** (Доступ.КодДоступа Set end)

                // *** End programmer edit section *** (Доступ.КодДоступа Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.Комната CustomAttributes)

        // *** End programmer edit section *** (Доступ.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Hotel.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.Комната Get start)

                // *** End programmer edit section *** (Доступ.Комната Get start)
                IIS.Hotel.Комната result = this.fКомната;
                // *** Start programmer edit section *** (Доступ.Комната Get end)

                // *** End programmer edit section *** (Доступ.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.Комната Set start)

                // *** End programmer edit section *** (Доступ.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (Доступ.Комната Set end)

                // *** End programmer edit section *** (Доступ.Комната Set end)
            }
        }
        
        /// <summary>
        /// Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Доступ.РегистрЗаписи CustomAttributes)

        // *** End programmer edit section *** (Доступ.РегистрЗаписи CustomAttributes)
        public virtual IIS.Hotel.DetailArrayOfРегистрЗаписи РегистрЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Get start)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Get start)
                if ((this.fРегистрЗаписи == null))
                {
                    this.fРегистрЗаписи = new IIS.Hotel.DetailArrayOfРегистрЗаписи(this);
                }
                IIS.Hotel.DetailArrayOfРегистрЗаписи result = this.fРегистрЗаписи;
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Get end)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Set start)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Set start)
                this.fРегистрЗаписи = value;
                // *** Start programmer edit section *** (Доступ.РегистрЗаписи Set end)

                // *** End programmer edit section *** (Доступ.РегистрЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоступE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоступE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоступE", typeof(IIS.Hotel.Доступ));
                }
            }
            
            /// <summary>
            /// "ДоступL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоступL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоступL", typeof(IIS.Hotel.Доступ));
                }
            }
        }
    }
}
