//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Hotel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись гостя.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьГостя CustomAttributes)

    // *** End programmer edit section *** (ЗаписьГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Запись гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьГостяE", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Гости as \'Гости\'",
            "Гости.Имя as \'Имя\'",
            "Гости.Фамилия as \'Фамилия\'",
            "Гости.Отчество as \'Отчество\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.КодCотрудника as \'Код сотрудника\'",
            "Комментарий as \'Комментарий\'"}, Hidden=new string[] {
            "Гости.Имя",
            "Гости.Фамилия",
            "Гости.Отчество",
            "Сотрудник.КодCотрудника"})]
    [MasterViewDefineAttribute("ЗаписьГостяE", "Гости", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [MasterViewDefineAttribute("ЗаписьГостяE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ЗаписьГостяL", new string[] {
            "КодЗаписи as \'Код записи\'",
            "Гости.Имя as \'Имя\'",
            "Гости.Фамилия as \'Фамилия\'",
            "Гости.Отчество as \'Отчество\'",
            "Сотрудник.КодCотрудника as \'Код Сотрудника\'",
            "Комментарий as \'Комментарий\'"})]
    public class ЗаписьГостя : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаписи;
        
        private string fКомментарий;
        
        private IIS.Hotel.Сотрудник fСотрудник;
        
        private IIS.Hotel.Гости fГости;
        
        // *** Start programmer edit section *** (ЗаписьГостя CustomMembers)

        // *** End programmer edit section *** (ЗаписьГостя CustomMembers)

        
        /// <summary>
        /// КодЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьГостя.КодЗаписи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьГостя.КодЗаписи CustomAttributes)
        public virtual int КодЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьГостя.КодЗаписи Get start)

                // *** End programmer edit section *** (ЗаписьГостя.КодЗаписи Get start)
                int result = this.fКодЗаписи;
                // *** Start programmer edit section *** (ЗаписьГостя.КодЗаписи Get end)

                // *** End programmer edit section *** (ЗаписьГостя.КодЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьГостя.КодЗаписи Set start)

                // *** End programmer edit section *** (ЗаписьГостя.КодЗаписи Set start)
                this.fКодЗаписи = value;
                // *** Start programmer edit section *** (ЗаписьГостя.КодЗаписи Set end)

                // *** End programmer edit section *** (ЗаписьГостя.КодЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьГостя.Комментарий CustomAttributes)

        // *** End programmer edit section *** (ЗаписьГостя.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Комментарий Get start)

                // *** End programmer edit section *** (ЗаписьГостя.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (ЗаписьГостя.Комментарий Get end)

                // *** End programmer edit section *** (ЗаписьГостя.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Комментарий Set start)

                // *** End programmer edit section *** (ЗаписьГостя.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (ЗаписьГостя.Комментарий Set end)

                // *** End programmer edit section *** (ЗаписьГостя.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Запись гостя.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьГостя.Гости CustomAttributes)

        // *** End programmer edit section *** (ЗаписьГостя.Гости CustomAttributes)
        [PropertyStorage(new string[] {
                "Гости"})]
        [NotNull()]
        public virtual IIS.Hotel.Гости Гости
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Гости Get start)

                // *** End programmer edit section *** (ЗаписьГостя.Гости Get start)
                IIS.Hotel.Гости result = this.fГости;
                // *** Start programmer edit section *** (ЗаписьГостя.Гости Get end)

                // *** End programmer edit section *** (ЗаписьГостя.Гости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Гости Set start)

                // *** End programmer edit section *** (ЗаписьГостя.Гости Set start)
                this.fГости = value;
                // *** Start programmer edit section *** (ЗаписьГостя.Гости Set end)

                // *** End programmer edit section *** (ЗаписьГостя.Гости Set end)
            }
        }
        
        /// <summary>
        /// Запись гостя.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьГостя.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ЗаписьГостя.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Hotel.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Сотрудник Get start)

                // *** End programmer edit section *** (ЗаписьГостя.Сотрудник Get start)
                IIS.Hotel.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ЗаписьГостя.Сотрудник Get end)

                // *** End programmer edit section *** (ЗаписьГостя.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьГостя.Сотрудник Set start)

                // *** End programmer edit section *** (ЗаписьГостя.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ЗаписьГостя.Сотрудник Set end)

                // *** End programmer edit section *** (ЗаписьГостя.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьГостяE", typeof(IIS.Hotel.ЗаписьГостя));
                }
            }
            
            /// <summary>
            /// "ЗаписьГостяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьГостяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьГостяL", typeof(IIS.Hotel.ЗаписьГостя));
                }
            }
        }
    }
}
